# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message_subject', models.CharField(max_length=200)),
                ('message_body', models.CharField(max_length=1000)),
                ('message_datetime', models.DateTimeField(verbose_name='message datetime')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=100)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_dob', models.CharField(max_length=20)),
                ('user_creation_datetime', models.DateTimeField(default=datetime.datetime(2016, 4, 26, 18, 13, 59, 154001, tzinfo=utc), verbose_name='creation datetime')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.User'),
        ),
    ]
