# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_dob', models.CharField(max_length=10)),
            ],
        ),
    ]
