# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 18, 14, 10, 437906, tzinfo=utc), verbose_name='creation datetime'),
        ),
    ]
