# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_dob',
            field=models.DateField(),
        ),
    ]
