# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 22:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20160404_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message_subject', models.CharField(max_length=200)),
                ('message_body', models.CharField(max_length=1000)),
                ('message_datetime', models.DateTimeField(verbose_name='message datetime')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 22, 19, 45, 253811, tzinfo=utc), verbose_name='creation datetime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.User'),
        ),
    ]
