# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20160418_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 22, 13, 28, 773801, tzinfo=utc), verbose_name='creation datetime'),
        ),
    ]
